version: '3'
services:
  node:
    build: ./
    container_name: nexttapp
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    command: sh -c "npm run build &&
             npm start"       
    depends_on:
      - django