import Head from 'next/head'
import React from 'react';
import {Inter} from '@next/font/google'

import Link from "next/link";

import Header from '../components/common/Header/Header';


const inter = Inter({subsets: ['latin']})

export default function Home() {
    return (

    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400&display=swap" rel="stylesheet"/> */}
    
      </Head>
      <Header/>
    </>
  )
}